"""
Script para convertir un dump SQL de MySQL/MariaDB a PostgreSQL.
Maneja la conversión de tipos de datos, sintaxis, e insertos binarios.
"""
import re
import sys
from pathlib import Path


def convert_mysql_to_postgres(input_file: str, output_file: str):
    """Convierte un archivo SQL de MySQL/MariaDB a PostgreSQL."""
    
    print(f"📖 Leyendo {input_file}...")
    with open(input_file, 'r', encoding='utf-8', errors='replace') as f:
        content = f.read()
    
    print(f"🔄 Convirtiendo sintaxis...")
    
    # 1. Eliminar comentarios MySQL específicos
    content = re.sub(r'/\*!\d+\s+.*?\*/;?', '', content, flags=re.DOTALL)
    
    # 2. Eliminar SET de MySQL
    content = re.sub(r'^SET\s+SQL_MODE.*?;$', '', content, flags=re.MULTILINE)
    content = re.sub(r'^SET\s+time_zone.*?;$', '', content, flags=re.MULTILINE)
    content = re.sub(r'^SET\s+@OLD.*?;$', '', content, flags=re.MULTILINE)
    content = re.sub(r'^SET\s+NAMES.*?;$', '', content, flags=re.MULTILINE)
    content = re.sub(r'^START TRANSACTION;$', '', content, flags=re.MULTILINE)
    content = re.sub(r'^COMMIT;$', '', content, flags=re.MULTILINE)
    
    # 3. Eliminar CREATE DATABASE y USE (PostgreSQL las maneja diferente)
    content = re.sub(r'^CREATE DATABASE.*?;$', '', content, flags=re.MULTILINE | re.IGNORECASE)
    content = re.sub(r'^use\s+\w+;$', '', content, flags=re.MULTILINE | re.IGNORECASE)
    
    # 4. Convertir backticks a comillas dobles
    content = re.sub(r'`([^`]+)`', r'"\1"', content)
    
    # 5. Convertir tipos de datos
    type_conversions = [
        # int variants
        (r'\bint\(\d+\)\s+NOT\s+NULL\s+AUTO_INCREMENT\b', 'SERIAL'),
        (r'\bint\(\d+\)\s+AUTO_INCREMENT\b', 'SERIAL'),
        (r'\btinyint\(1\)\b', 'BOOLEAN'),
        (r'\btinyint\(\d+\)\b', 'SMALLINT'),
        (r'\bsmallint\(\d+\)\b', 'SMALLINT'),
        (r'\bmediumint\(\d+\)\b', 'INTEGER'),
        (r'\bint\(\d+\)\b', 'INTEGER'),
        (r'\bbigint\(\d+\)\b', 'BIGINT'),
        # decimal/float
        (r'\bdouble\b', 'DOUBLE PRECISION'),
        (r'\bfloat\(\d+,\d+\)\b', 'REAL'),
        # text/blob
        (r'\blongblob\b', 'BYTEA'),
        (r'\bmediumblob\b', 'BYTEA'),
        (r'\btinyblob\b', 'BYTEA'),
        (r'\bblob\b', 'BYTEA'),
        (r'\blongtext\b', 'TEXT'),
        (r'\bmediumtext\b', 'TEXT'),
        (r'\btinytext\b', 'TEXT'),
        # date/time
        (r'\bdatetime\b', 'TIMESTAMP'),
        # enum (PostgreSQL no soporta enum inline, convertir a VARCHAR)
        (r"enum\([^)]+\)", 'VARCHAR(255)'),
    ]
    
    for pattern, replacement in type_conversions:
        content = re.sub(pattern, replacement, content, flags=re.IGNORECASE)
    
    # 6. Eliminar ENGINE, DEFAULT CHARSET, COLLATE
    content = re.sub(r'\)\s*ENGINE=\w+(\s+DEFAULT\s+CHARSET=\w+)?(\s+COLLATE=\S+?)?(\s+AUTO_INCREMENT=\d+)?(\s+ROW_FORMAT=\S+?)?\s*;',
                     ');', content, flags=re.IGNORECASE)
    
    # 7. Eliminar COLLATE en columnas
    content = re.sub(r'\s+COLLATE\s+\S+', '', content, flags=re.IGNORECASE)
    content = re.sub(r'\s+CHARACTER\s+SET\s+\w+', '', content, flags=re.IGNORECASE)
    
    # 8. Convertir UNSIGNED (PostgreSQL no lo soporta, ignorar)
    content = re.sub(r'\s+UNSIGNED\b', '', content, flags=re.IGNORECASE)
    
    # 9. Eliminar KEY/INDEX dentro de CREATE TABLE (PostgreSQL los crea por separado)
    # Esto se hará después con ALTER TABLE
    
    # 10. Convertir LOCK TABLES / UNLOCK TABLES (no existe en PG)
    content = re.sub(r'^LOCK TABLES.*?;$', '', content, flags=re.MULTILINE | re.IGNORECASE)
    content = re.sub(r'^UNLOCK TABLES.*?;$', '', content, flags=re.MULTILINE | re.IGNORECASE)
    
    # 11. Convertir ALTER TABLE ... AUTO_INCREMENT
    content = re.sub(r'AUTO_INCREMENT\s*=\s*\d+', '', content, flags=re.IGNORECASE)
    
    # 12. Convertir hexadecimal binary literals 0x... a formato PostgreSQL
    # MySQL: INSERT ... VALUES (..., 0xFFD8FF..., ...)
    # PG:    INSERT ... VALUES (..., decode('FFD8FF...', 'hex'), ...)
    def hex_to_pg(match):
        hex_data = match.group(1)
        return f"decode('{hex_data}', 'hex')"
    
    content = re.sub(r"0x([0-9A-Fa-f]+)", hex_to_pg, content)
    
    # 13. Convertir comillas escapadas \' a ''
    # MySQL usa \' o '' para escapar, PostgreSQL usa ''
    # (Esto es delicado, lo dejamos por ahora ya que el dump generalmente usa '')
    
    # 14. Convertir "\\" (backslash escapado) - PostgreSQL necesita E'' o standard_conforming_strings
    # Por simplicidad, agregamos encabezado para deshabilitar standard_conforming_strings temporalmente
    
    # 15. Eliminar líneas vacías múltiples
    content = re.sub(r'\n\s*\n\s*\n+', '\n\n', content)
    
    # 16. Agregar header de PostgreSQL
    header = """-- PostgreSQL converted dump from MySQL
-- Auto-generated by convert_mysql_to_postgres.py

SET standard_conforming_strings = off;
SET escape_string_warning = off;
SET client_encoding = 'UTF8';

"""
    
    content = header + content
    
    print(f"💾 Escribiendo {output_file}...")
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"✅ Conversión completada!")
    print(f"   Archivo: {output_file}")
    print(f"   Tamaño:  {Path(output_file).stat().st_size:,} bytes")


if __name__ == "__main__":
    input_file = sys.argv[1] if len(sys.argv) > 1 else "init.sql"
    output_file = sys.argv[2] if len(sys.argv) > 2 else "init_postgres.sql"
    convert_mysql_to_postgres(input_file, output_file)
