"""
Convertidor de dump MySQL a PostgreSQL para el proyecto Glifos Mayas.

Maneja:
- Eliminar sentencias y comentarios específicos de MySQL
- Backticks `name` → "name"
- Tipos: int(N) → INTEGER, tinyint → BOOLEAN, blob → BYTEA
- ENGINE=InnoDB DEFAULT CHARSET=... → eliminado
- AUTO_INCREMENT → SERIAL/IDENTITY usando sequences
- BLOB hex literals 0xABCD → decode('ABCD', 'hex')
- ALTER TABLE ... MODIFY ... AUTO_INCREMENT=N → setval(...)
- ADD UNIQUE KEY name (col) → ADD CONSTRAINT name UNIQUE (col)
- ADD KEY name (col) → CREATE INDEX name ON table (col)
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# Mapeo de columnas auto-increment por tabla detectadas en el init.sql
AUTO_INC_COLUMNS: dict[str, str] = {
    "t_attributes": "id_attribute",
    "t_distinction": "id_distinction",
    "t_general": "num",
    "t_general_busqueda": "num",
    "t_general_thomson_number": "num",
    "t_general_transcription": "num",
    "t_general_traslation": "num",
    "t_refo": "num_refo",
    "t_traduccion": "num_traduccion",
    "t_transcripcion": "num_transcrpcion",
    "t_usuarios": "id_usuario",
}


def strip_mysql_directives(sql: str) -> str:
    """Elimina directivas y comentarios condicionales de MySQL."""
    # /*!40101 ... */;
    sql = re.sub(r"/\*!\d+[^*]*\*/;?", "", sql)
    # SET SQL_MODE = ...
    sql = re.sub(r"^SET SQL_MODE.*?;\s*$", "", sql, flags=re.MULTILINE)
    # SET time_zone = ...
    sql = re.sub(r"^SET time_zone.*?;\s*$", "", sql, flags=re.MULTILINE)
    return sql


def remove_create_database(sql: str) -> str:
    """PostgreSQL crea la BD desde POSTGRES_DB env; quitamos CREATE DATABASE/USE."""
    sql = re.sub(r"^CREATE DATABASE[^;]*;\s*$", "", sql, flags=re.MULTILINE | re.IGNORECASE)
    sql = re.sub(r"^use\s+\w+\s*;\s*$", "", sql, flags=re.MULTILINE | re.IGNORECASE)
    return sql


def replace_backticks(sql: str) -> str:
    """Convierte `identificador` a "identificador"."""
    return sql.replace("`", '"')


def replace_types(sql: str) -> str:
    """Convierte tipos MySQL a PostgreSQL."""
    # int(11) y similares → INTEGER
    sql = re.sub(r"\bint\(\d+\)", "INTEGER", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\btinyint\(\d+\)", "SMALLINT", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\bsmallint\(\d+\)", "SMALLINT", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\bbigint\(\d+\)", "BIGINT", sql, flags=re.IGNORECASE)
    # blob → BYTEA
    sql = re.sub(r"\b(long|medium|tiny)?blob\b", "BYTEA", sql, flags=re.IGNORECASE)
    # datetime → TIMESTAMP
    sql = re.sub(r"\bdatetime\b", "TIMESTAMP", sql, flags=re.IGNORECASE)
    return sql


def remove_engine_charset(sql: str) -> str:
    """Elimina ENGINE=... DEFAULT CHARSET=... del final de CREATE TABLE."""
    sql = re.sub(
        r"\)\s*ENGINE\s*=\s*\w+\s*(?:DEFAULT\s+CHARSET\s*=\s*\w+)?\s*(?:COLLATE\s*=\s*\w+)?\s*;",
        ");",
        sql,
        flags=re.IGNORECASE,
    )
    return sql


def convert_hex_blobs(sql: str) -> str:
    """Convierte literales hex 0xABCD a decode('ABCD','hex')."""
    # Match 0x seguido de pares hex
    return re.sub(
        r"0x([0-9a-fA-F]+)",
        lambda m: f"decode('{m.group(1)}', 'hex')",
        sql,
    )


def convert_auto_increment_in_create(sql: str) -> str:
    """
    En el CREATE TABLE, las columnas con AUTO_INCREMENT no existen como tal en init.sql
    (porque MySQL las separa en ALTER), pero por si acaso las convertimos a SERIAL.
    """
    # "id" INTEGER NOT NULL AUTO_INCREMENT → "id" SERIAL NOT NULL
    sql = re.sub(
        r'(\"\w+\")\s+INTEGER\s+NOT\s+NULL\s+AUTO_INCREMENT',
        r"\1 SERIAL NOT NULL",
        sql,
        flags=re.IGNORECASE,
    )
    return sql


def convert_alter_auto_increment(sql: str) -> str:
    """
    Convierte:
      ALTER TABLE "tname"
        MODIFY "col" INTEGER NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=N;
    en:
      ALTER TABLE "tname" ALTER COLUMN "col" ADD GENERATED BY DEFAULT AS IDENTITY (START WITH N);
    Pero como ya creamos secuencias con SERIAL via post-procesamiento,
    aquí solo emitimos un setval.
    """
    pattern = re.compile(
        r'ALTER\s+TABLE\s+"(\w+)"\s*\n?\s*MODIFY\s+"(\w+)"\s+[^,]+,\s*AUTO_INCREMENT\s*=\s*(\d+)\s*;',
        flags=re.IGNORECASE,
    )

    def repl(m: re.Match) -> str:
        table = m.group(1)
        col = m.group(2)
        value = m.group(3)
        seq_name = f"{table}_{col}_seq"
        return (
            f"-- AUTO_INCREMENT migrado a sequence\n"
            f"SELECT setval('{seq_name}', {value}, false);"
        )

    return pattern.sub(repl, sql)


def convert_keys(sql: str) -> str:
    """
    Convierte:
      ALTER TABLE "t" ADD KEY "name" ("col");
      → CREATE INDEX "name" ON "t" ("col");
      ALTER TABLE "t" ADD UNIQUE KEY "name" ("col");
      → ALTER TABLE "t" ADD CONSTRAINT "name" UNIQUE ("col");
    Como vienen en bloques tipo:
      ALTER TABLE "t"
        ADD PRIMARY KEY (...),
        ADD UNIQUE KEY "name" (...),
        ADD KEY "name" (...);
    procesamos línea por línea dentro del bloque.
    """
    lines = sql.split("\n")
    out: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        m = re.match(r'\s*ALTER\s+TABLE\s+"(\w+)"\s*$', line, flags=re.IGNORECASE)
        if not m:
            out.append(line)
            i += 1
            continue

        table = m.group(1)
        # Recolectamos el cuerpo del ALTER TABLE hasta el ;
        body_lines: list[str] = []
        i += 1
        while i < len(lines):
            body_lines.append(lines[i])
            if lines[i].rstrip().endswith(";"):
                break
            i += 1
        i += 1

        body = "\n".join(body_lines)
        # Si contiene AUTO_INCREMENT lo dejamos pasar (se procesa en otra función)
        if "AUTO_INCREMENT" in body.upper():
            out.append(line)
            out.extend(body_lines)
            continue

        # Quitamos el ; final
        body = body.rstrip().rstrip(";")

        # Partimos por comas a nivel superior (asumimos sin paréntesis anidados con comas)
        parts = split_top_level_commas(body)

        emitted_alters: list[str] = []
        extra_statements: list[str] = []

        for part in parts:
            part_stripped = part.strip()
            # ADD PRIMARY KEY (...)
            if re.match(r"ADD\s+PRIMARY\s+KEY", part_stripped, flags=re.IGNORECASE):
                emitted_alters.append("  " + part_stripped)
                continue
            # ADD UNIQUE KEY "name" (cols)
            um = re.match(
                r'ADD\s+UNIQUE\s+KEY\s+"(\w+)"\s*\(([^)]+)\)',
                part_stripped,
                flags=re.IGNORECASE,
            )
            if um:
                name = um.group(1)
                cols = um.group(2)
                # Para evitar conflictos de nombre con índices, prefijamos
                emitted_alters.append(
                    f'  ADD CONSTRAINT "uq_{table}_{name}" UNIQUE ({cols})'
                )
                continue
            # ADD KEY "name" (cols)
            km = re.match(
                r'ADD\s+KEY\s+"(\w+)"\s*\(([^)]+)\)',
                part_stripped,
                flags=re.IGNORECASE,
            )
            if km:
                name = km.group(1)
                cols = km.group(2)
                extra_statements.append(
                    f'CREATE INDEX IF NOT EXISTS "ix_{table}_{name}" ON "{table}" ({cols});'
                )
                continue
            # Default: lo mantenemos
            emitted_alters.append("  " + part_stripped)

        if emitted_alters:
            out.append(f'ALTER TABLE "{table}"')
            out.append(",\n".join(emitted_alters) + ";")
        out.extend(extra_statements)

    return "\n".join(out)


def split_top_level_commas(text: str) -> list[str]:
    """Divide texto por comas no contenidas en paréntesis."""
    parts: list[str] = []
    depth = 0
    current: list[str] = []
    for ch in text:
        if ch == "(":
            depth += 1
            current.append(ch)
        elif ch == ")":
            depth -= 1
            current.append(ch)
        elif ch == "," and depth == 0:
            parts.append("".join(current))
            current = []
        else:
            current.append(ch)
    if current:
        parts.append("".join(current))
    return parts


def upgrade_auto_inc_columns_in_create(sql: str) -> str:
    """
    Como en el CREATE TABLE las columnas auto-increment vienen como INTEGER NOT NULL,
    necesitamos volverlas SERIAL para que PostgreSQL cree la sequence.
    Esto hace match con el diccionario AUTO_INC_COLUMNS.
    """
    for table, col in AUTO_INC_COLUMNS.items():
        # Buscar el CREATE TABLE de esta tabla y modificar solo la columna autoincr
        create_pattern = re.compile(
            r'(CREATE\s+TABLE\s+"' + re.escape(table) + r'"\s*\()(.*?)(\n\s*\)\s*;)',
            flags=re.IGNORECASE | re.DOTALL,
        )

        def repl(m: re.Match) -> str:
            head = m.group(1)
            body = m.group(2)
            tail = m.group(3)
            # Reemplazar "col" INTEGER NOT NULL → "col" SERIAL
            new_body = re.sub(
                r'("' + re.escape(col) + r'")\s+INTEGER\s+NOT\s+NULL',
                r"\1 SERIAL",
                body,
                count=1,
                flags=re.IGNORECASE,
            )
            return head + new_body + tail

        sql = create_pattern.sub(repl, sql)
    return sql


def add_postgres_header(sql: str) -> str:
    """Añade encabezado claro para PostgreSQL."""
    header = (
        "-- =========================================================\n"
        "-- Glifos Mayas - Esquema inicial PostgreSQL (auto-generado)\n"
        "-- Convertido desde init.sql (MySQL) por scripts/convert_mysql_to_postgres.py\n"
        "-- =========================================================\n\n"
    )
    return header + sql


def main() -> int:
    src = Path("db/init.sql")
    dst = Path("db/init.sql")

    if len(sys.argv) > 1:
        src = Path(sys.argv[1])
    if len(sys.argv) > 2:
        dst = Path(sys.argv[2])

    sql = src.read_text(encoding="utf-8", errors="replace")

    # Pipeline de transformaciones (orden importa)
    sql = strip_mysql_directives(sql)
    sql = remove_create_database(sql)
    sql = replace_backticks(sql)
    sql = replace_types(sql)
    sql = remove_engine_charset(sql)
    sql = convert_hex_blobs(sql)
    sql = upgrade_auto_inc_columns_in_create(sql)
    sql = convert_alter_auto_increment(sql)
    sql = convert_keys(sql)
    sql = add_postgres_header(sql)

    # Limpiar líneas en blanco múltiples
    sql = re.sub(r"\n{3,}", "\n\n", sql)

    dst.write_text(sql, encoding="utf-8")
    print(f"OK -> {dst} ({len(sql):,} chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
